### ISSUE TITLE
Redeem causes Portfolio Contents section to double up all entries + missing k-eth + Fund invest/redeem history

### ISSUE THREAD

**Issue by thehighfiveghost** [melonproject/portal#121]
I tried to redeem some of the K-ETH I'd invested at the same rate I initially invested in the fund (1 K-ETH per share). I don't seem to be getting any of that Ether back in my wallet, but it seems to have been deducted from the fund holdings. Where did it go?

Also, this process seems to have irrecovably doubled all the entries in my portfolio contents section as seen here: https://ibb.co/iGcXJ5

Finally, could be a cool future feature to see the history of successful fund invest/redeems so it's easier to keep track! :)

**Comment by retotrinkler** [comment]
Double entries have been solved - other parts split up in individual issues (see references above)
