### ISSUE TITLE
Space in Wallet and Portfolio page

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/portal#142]
![screenshot from 2017-05-19 13-00-32](https://cloud.githubusercontent.com/assets/13721565/26245164/2a1a3ff0-3c93-11e7-8408-c6e6361dcc6e.png)
There sometimes appears some empty whitespace on wallet and portfolio page

**Comment by schmidsi** [comment]
This is because the MetricsGraphics and D3 visualisations are both there.
- [ ] Remove Metrics Graphics completely
