### ISSUE TITLE
Description of Order Book graph seems to be out of place

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/portal#151]
![screenshot from 2017-05-22 14-18-43](https://cloud.githubusercontent.com/assets/13721565/26308465/a927cc00-3ef9-11e7-8bec-d459d69dcce2.png)

would be nice if this one is in the top right corner of the graph

**Comment by schmidsi** [comment]
Its actually a bug :(

**Comment by retotrinkler** [comment]
due to currently not using orderbook graph am going to close this
