### ISSUE TITLE
Removing Graphs on Wallet and Portfolio page

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/portal#153]
Think for 0.1.0 release we omit the graphs on _Wallet_ and _Portfolio_ page (we always can include later again)

Instead could be header and paragraph in style like this: https://github.com/melonproject/portal/blob/116d73919c14d15cf6c3be205349bca4d1999eeb/imports/ui/components/ux/ux_pages.html#L39-L40

- Where header for Wallet page could be: `Wallet`
and paragraph: `Overview of your Ethereum Wallet`
- and header for Portfolio page could be: `Portfolio`
and paragraph: `Overview of your Melon Portfolio`

**Comment by schmidsi** [comment]
The graphs are already removed with #141.

**Comment by retotrinkler** [comment]
ah ok super
