### ISSUE TITLE
Lookup call for Manage page address

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/portal#175]
Eg http://localhost:3000/manage/0x11a3060066bff1025f6f658344da523bd0b7352a

something along the lines of

```
  const address = FlowRouter.getParam('address');
  const doc = Cores.findOne({ owner: address });
  if (doc === undefined || address === undefined) return;
  if (doc.count() !== 0) -> Set session for button to true
  else Set session for button to false
```

**Comment by schmidsi** [comment]
Is it a fund address or account?

If fund? --> set session fromPortfolio true
Else --> false

**Comment by schmidsi** [comment]
- [ ] Change the address in the url if button is clicked
