### ISSUE TITLE
Loss of access to funds when investing at a wrong ETH/Share price

### ISSUE THREAD

**Issue by jbergh** [melonproject/portal#237]
Trying to invest in a fund and adjusting the ETH/Share price to a number different from 1.0 results in a loss of access to the funds (and there are only two Metamask popups, not a third one). It states _“Oops, an error has occured. Please verify that your holdings allow you to invest in this fund!”_ 
The amount that is invested is subtracted from the wallet but does not show up in the fund and no shares are created. **(Also note the typo in the error message "occured" should be "occurred")**

If I'm not mistaken there was no option to specify a ETH/Share price different from 1.0 when creating the fund.

This is what I did:
1. Creation of fund - https://kovan.etherscan.io/tx/0x5bcb8d0ba4d17bd1b0199e5cb62a4c1cbe9ad4e8d3d3f77a3b1d2652ca708e7d
2. Attempt 1 to invest at a ‘wrong’ ETH/share (lower than 1ETH/share) price (popup 1) -  https://kovan.etherscan.io/tx/0x0de2b5b5dd4910ee3bce5026ab088b7091ea7e3788995084913b49881cc7f208
3. Popup 2 - https://kovan.etherscan.io/tx/0x7d711661e63934ac64d6c8a086140b6282da53bef7befae6e03806843de54b76
4. No popup 3 - no shares created & loss of access to funds?
5. Attempt 1 to invest at a ‘wrong’ ETH/share (lower than 1ETH/share) price (popup 1) - https://kovan.etherscan.io/tx/0xf3b0b053d9d51b68a55d03d4d27d409c48c81ad9d048f268ff90aa1acbddbff7
6. Popup 2 - https://kovan.etherscan.io/tx/0xa288d4771045412ad1f1f43526f8868dd233d4b940af92617defc6a9046c895c
7. No popup 3 - no shares created & loss of access to funds?
8. Attempt 2 to invest at ‘correct’ ETH/share price (1ETH/share, popup 1) - https://kovan.etherscan.io/tx/0x5289297b7b43a6a68a919049863d6fb9d1b0ccb5818537b1f12d7b36daf67c50
9. Popup 2 - https://kovan.etherscan.io/tx/0xd345bc911e4fe9a6e6369513ae29296f4ea57d83c4761d242ba556d343ddc6f3
10. Popup 3, Shares successfully created - https://kovan.etherscan.io/tx/0xc1df23eff7e26f2f82d005e25440fb1d616c8acbf4a3c0577771b2173e20fd7c
11. I was actually able to invest a second time and create more shares at a price of 1.0 ETH/share (before any fund-management action, after that investing was not possible anymore, just like you indicated in the blog post)

**Comment by schmidsi** [comment]
Thanks @jbergh for the detailed issue. I think we should just fix the share-price at 1 ETH/Share in the beginning and lock the field to whatever is calculated later.

I.e. Just make the field readonly.

Or are there any use cases where a fund manager would need a different share price in the beginning or has to change the share price later on? @retotrinkler @perhamgirl ?
