### ISSUE TITLE
Melon Exchange and Cryptocompare links on Create new fund page are broken

### ISSUE THREAD

**Issue by pzagor2** [melonproject/portal#244]
I'm not sure where the link should point to, but currently, they are pointing to https://daemon.melonport.com/oracle and https://daemon.melonport.com/liquidityprovider

Unfortunately, both pages load with an empty white page and a meteorjs error saying that the route for this path does not exist.

**Comment by retotrinkler** [comment]
thanks for reporting

- cryptocompare should point to: https://kovan.etherscan.io/address/0x442Fd95C32162F914364C5fEFf27A0Dc05214706

- exchange should point to: https://kovan.etherscan.io/address/0x6afe9b834025284688c693789f1c1af710b89776

**Comment by pzagor2** [comment]
I created a pull request that should fix these links. 

https://github.com/melonproject/portal/pull/245

**Comment by jennazenk** [comment]
closed w #245
