### ISSUE TITLE
Errors after first setup

### ISSUE THREAD

**Issue by fabiosalvi** [melonproject/portal#254]
NOTE: I've used the current `master` branch.

- At the end of `meteor npm install` I get this one:
![schermata 2017-06-15 alle 17 41 12](https://user-images.githubusercontent.com/29264173/27189527-ef555534-51f1-11e7-82a5-ab8641a0ae83.png)

but it seems no big deal.

- After  `npm start`I get a blank screen on http://localhost:3000/ and some errors in console:
![schermata 2017-06-15 alle 17 50 19](https://user-images.githubusercontent.com/29264173/27189931-2ef64440-51f3-11e7-8656-a26594831b66.png)

These are mostly due to the use of an adBlocker (I use uBlock). 
[issue #32 on okgrow](https://github.com/okgrow/analytics/issues/32)

Once turned off and reloaded the portal finally shows up, but some errors are still there:
![schermata 2017-06-15 alle 17 52 56](https://user-images.githubusercontent.com/29264173/27190050-87ee65be-51f3-11e7-8e38-395a766427a6.png)

**Comment by schmidsi** [comment]
The last screenshot looks ok. The yellow entries (do not use window.web3) are just deprecation warning. Also, you can ignore the "Missing analyticSettings" because we don't track on development machines.

Does it work otherwise?

**Comment by fabiosalvi** [comment]
Oh yes, it works well and has a nice vibe! :-)

How I am supposed to switch from window.web3. to the imported web3.js?

Also, I see that the web3.js is in `/imports/redux/web3.js` now.

BTW, the transition from sessions to Redux, when is supposed to begin?

**Comment by retotrinkler** [comment]
@fabiosalvi transition is ongoing :)

**Comment by retotrinkler** [comment]
@schmidsi is there anything we can do about `window.web3` warnings

**Comment by retotrinkler** [comment]
going to close this for now as main issue seems to be resolved
