### ISSUE TITLE
investment put into another (unknown?) fund

### ISSUE THREAD

**Issue by d-moos** [melonproject/portal#264]
Hey guys,

Whenever I try to invest something into my fund (https://portal.melonport.com/fund/0xf50553d5ff2a40f9e4cc6a0a0e199871d0f3a93d) it does end up here (https://portal.melonport.com/fund/0x7506c7bfed179254265d443856ef9bda19221cd7).

The transaction which is being requested is always targeted at the unknown fund. When I accept the transaction, the portal will keep asking me to send ether to the unkown contract until I start to reject it.

It's pretty hard to explain so I recorded a small video (https://youtu.be/5_Z6biBGAss).
Am I doing anything wrong here?

**Comment by jennazenk** [comment]
I close this one and split it into the following issues:
#266 #267 and #268
