### ISSUE TITLE
Some minor text issues

### ISSUE THREAD

**Issue by greggdourgarian** [melonproject/portal#270]
Hi Melon friends,
I have tried out the interface today.  

1.  AUM is not a well known acronym for many of us potential asset managers.  Suggest this get spelled out or at least displayed in full when hovering.
2. Capitalization is not consistent.  Example: Personal Stake vs Value of personal stake vs Share Price
3. Under Fund Investment "Volume" s/b "Amount" or "Units".  "Volume" usually conveys the sum of transactions in a period and is out of place.
4. Under 'Recent Trades' the column "Buy Price" should just be "Price" since the column may contain both Buy and Sell prices.
5.  Also under 'Recent Trades' the column header "Vol" should not be shortened and - i think - should be 'Units' or 'Amount'.

**Comment by retotrinkler** [comment]
Thanks
1. Think we should spell it out in fund page in fund overview section
2. Agree
3. I'd be in favor of _Amount_
4. Agree
5. I'd be in favor of _Amount_

**Comment by jennazenk** [comment]
closed this in #285
