### ISSUE TITLE
Melon Summary "Status" msg when not connected to kovan and/or account unlocked

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/portal#271]
![screenshot from 2017-06-21 17-57-49](https://user-images.githubusercontent.com/13721565/27394102-491b4610-56ab-11e7-8ed4-0bbf073dd05d.png)

Melon Summary "Status" there should be a msg informing user about status (instead of being empty)
status msg could be same as msg displayed below - in above screenshot this would be _No account selected_

**Comment by jennazenk** [comment]
closed this in #285
