### ISSUE TITLE
Having staging.melonport.com deployment options

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/portal#272]
For testing purposes etc

**Comment by retotrinkler** [comment]
can create CNAME record once ready

**Comment by schmidsi** [comment]
I deployed it to http://melon-stage.eu.meteorapp.com/.

@retotrinkler : If you add a `CNAME` from 
`staging.melonport.com` to `eu-west-1.galaxy-ingress.meteor.com`, I can change the deployment hostname.

**Comment by retotrinkler** [comment]
@schmidsi staging.melonport.com is set
