### ISSUE TITLE
K-eth faucet

### ISSUE THREAD

**Issue by perhamgirl** [melonproject/portal#275]
One piece of feedback is if we can make the Kovan ether faucet can be a big bottleneck for testers

Some ppl have tried testing but due to delay time in receiving K-eth, may lose momentum testing\

One suggestion:
can we add an option to sell some test K-eth? can be for a small nominal price to prevent spamming and we can limit the daily amount for example?

By same token. a couple of ppl complained about the assumption that everyone knows what kovan is - GH/myself will add a paragraph into the medium blog.

**Comment by retotrinkler** [comment]
agree - big bottleneck.
there is already a similar issue here #214
