### ISSUE TITLE
My onboarding experience

### ISSUE THREAD

**Issue by ricburton** [melonproject/portal#303]
the news and partners.

#What do I do now?
Where do I download the software? Where is the GitHub link? How do I get started? What do I do?

#Click on Portal
I am at a portal. It says no connection. No connection to what? Metamask? What is Metamask? Let’s install metmamask.

#MetaMask
Install metmamask. Go back to portal. Click refresh. No account selected. What account? What do I do with an account? I guess I should click the fox icon in Chrome.

Click accept on long ts-and-cs. Doesn’t work. Scroll down ts-and-cs. Click accept again. New screen to create a password. OK. Encrypt my new DEN. What is a DEN?

Copy the 12 words. OK. I’ll put that in 1Password. Done that.

Ok. I am in. *Now* the error is: “Well done you're connected with Metamask. Now switch to the Kovan network to use this application”

I have no idea how to switch to the Kovan network. What is the Kovan network? What do I do?

**Comment by ricburton** [comment]
Found the dropdown in MetaMask
<img width="258" alt="screen shot 2017-07-02 at 20 18 04" src="https://user-images.githubusercontent.com/438160/27772895-9443dbaa-5f63-11e7-9ebd-ca15d0d66ad7.png">

#Kovan
*Googles Kovan* 
https://medium.com/@Digix/announcing-kovan-a-stable-ethereum-public-testnet-10ac7cb6c85f
Sweet. Sounds like a good plan to have a test net. OK. Let's head back to Melonport.

#Insufficient Funds
Ok now I am on my third error state and I feel like a bit of a dummy. I would love the UI to be less accusatory—you don't have this—and instead be more of a supportive set-up guide. Let's get some K-Eth.

#The Kovan Faucet
What is this badboy? Another GitHub project? I wonder what I have to do here to get this faucet to spout forth copious sums of dreamy Kovan Ether.

OK, a gitter channel at: https://gitter.im/kovan-testnet/faucet

Then I politely post my request: Hello. I am doing some UX testing for Melonport. I have come down the rabbit hole and reached this stage. Please can I get some Kovan Ether.

I go to MetaMask to find my address: 0x8F12DA507508138993EB3BAA610D18E036cD9936

I now wait with baited breath...

**Comment by schmidsi** [comment]
Hi Richard,

Thanks a lot for your feedback. It's highly valued. We know that it is a bit complicated to get started with MetaMask/Kovan and all this stuff. Did you read our [introductory blog post on medium](https://medium.com/melonport-blog/melon-v0-1-0-release-2a81102b03fd)? Surely, for the 0.2 release we will make more guides & documentation. Please be aware that this is the version 0.1 and still considered to be [bleeding edge](https://en.wikipedia.org/wiki/Bleeding_edge_technology).

But you did great already. So with Metamask installed, pointed to the Kovan test net, you only need some K-ETH to kick the tires. [Which I sent to you now](https://kovan.etherscan.io/address/0x8F12DA507508138993EB3BAA610D18E036cD9936).

Sorry for the delay, but even the hardest working blockchain warriors need to take a day off some times ;).

Thanks for your help, have fun. And feel free to open more issues if you have any suggestions or bugs spotted.

**Comment by ricburton** [comment]
Totally understand! For context, George asked me to look at Melonport through a designer's eyes :)

**Comment by schmidsi** [comment]
I see. To summarise your points:

- [ ] Better explanation of Metamask/Kovan (could be a short comic with screenshots)
- [ ] Automatically send some K-ETH to new users (we're working on this already)

Good?

**Comment by ricburton** [comment]
I think the setup process should take less than 60 seconds. I also have no idea what I actually get with a melonport fund.

The instant kovan sounds 👌🏼
