### ISSUE TITLE
Manual for noobs

### ISSUE THREAD

**Issue by CryptoTrade007** [melonproject/portal#315]
Hi,
can you provide some manual how to use Melonport. Some basic guides, how to buy stuff, how to invest into other portfolios?
I'm a bit lost in UI and what it should do.

**Comment by jennazenk** [comment]
hey @CryptoTrade007 
Here is a blog post that will walk you through how to use the portal. It also has a demo video:
https://medium.com/melonport-blog/melon-v0-1-0-release-2a81102b03fd

Let us know if anything is unclear! Feedback v much appreciated :)
