### ISSUE TITLE
do not allow zero volume orders

### ISSUE THREAD

**Issue by SCBuergel** [melonproject/portal#342]
the order book seems to currently contain an order of volume zero (bottom red order):
<img width="1164" alt="screen shot 2017-07-24 at 20 05 46" src="https://user-images.githubusercontent.com/11379673/28537530-84124ce0-70ab-11e7-9333-3b78aa877d0c.png">
I also selected that order and the one above it and made sure that this is not a display issue of a very very tiny order. This is likely a bug in the market maker bot for this competition phase.

**Comment by jennazenk** [comment]
I will close this one because I think it was a very very tiny order and since we only display 4 decimals on the frontend, and MLN has a precision of 18, the tiny amount is not actually displayed. We will think of ways to give the user more visibility on those tiny orders. Thanks Sebastian!

**Comment by SCBuergel** [comment]
Hi Jenna
> I think it was a very very tiny order and since we only display 4 decimals on the frontend, and MLN has a precision of 18
I do not think this was the case - that was my first assumption. I selected the order and then checked in the section on top which did show all decimal places (I think all 18 - not 100% sure but it was a LOT) and it was the exact same amount.
