### ISSUE TITLE
CORS Errors with api.coinmarketcap.com lookups

### ISSUE THREAD

**Issue by schmidsi** [melonproject/portal#38]
It seems that api.coinmarketcap.com did not configure their servers to enable [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS). Therefore, calls to those API endpoints fail from the client:

https://github.com/melonproject/portal/blob/1019b064cf6b27333320d8866cd2c61b860fe4bf/imports/startup/client/ux.js#L17
-->
> XMLHttpRequest cannot load https://api.coinmarketcap.com/v1/ticker/augur/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://portal.melonport.com' is therefore not allowed access.

I commented the corresponding lines out, since there is no scenario where they work. Possible solutions:
- Force coinmarketcap.com to enable CORS (prettiest solution)
- ~~Workaround with JSONP ~~ (also not supported by coinmarketcap.com
- Create a proxy

**Comment by retotrinkler** [comment]
we could try cryptocompare instead

**Comment by retotrinkler** [comment]
initial version implementend in PR #68
