### ISSUE TITLE
24h Change on Portfolio page as on Wallet page

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/portal#71]
![screenshot from 2017-05-04 08-54-37](https://cloud.githubusercontent.com/assets/13721565/25693082/5dcc25b8-30a7-11e7-8854-f5e84cd8adc7.png)
![screenshot from 2017-05-04 08-54-26](https://cloud.githubusercontent.com/assets/13721565/25693083/5de0e7be-30a7-11e7-9f01-b823b582c8f0.png)

**Comment by peterdraw** [comment]
Fixed here #81
