### ISSUE TITLE
From Portfolio button design

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/portal#77]
![screenshot from 2017-05-04 11-49-45](https://cloud.githubusercontent.com/assets/13721565/25698620/ce09eb72-30bf-11e7-9b15-1a538db056d4.png)

**Comment by peterdraw** [comment]
I think it works well in my local. Will check with another browser.

![screen shot 2017-05-04 at 5 24 46 pm](https://cloud.githubusercontent.com/assets/9424987/25705118/56083a60-3106-11e7-8159-4fdd3ff21319.png)
![screen shot 2017-05-04 at 5 24 40 pm](https://cloud.githubusercontent.com/assets/9424987/25705119/561205f4-3106-11e7-987b-454d2af4ff95.png)

**Comment by retotrinkler** [comment]
hmm yeah for Firefox it also displays correctly

**Comment by retotrinkler** [comment]
can see error in Chromium browser version
`Version 58.0.3029.81 Built on Ubuntu , running on Ubuntu 17.04 (64-bit)` 
but its not that big of a deal seems to work w most commonly used browsers...

**Comment by peterdraw** [comment]
Yup, it also works correctly in Chrome Version 58.0.3029.96 (64-bit)

**Comment by retotrinkler** [comment]
closing this a button is currently removed
